#include "TString.h"
#include "TChain.h"
#include <iostream>
#include <TFile.h>
#include <TBranch.h>
void do_stuff(TString filename){
    
//    TString filename="raw_predictions_p8_ee_Zuds_ecm91_219.root";
    std::cout << filename << endl;
    TChain *tree1 = new TChain("tree","tree");
    TChain *tree2 = new TChain("tree","tree");
    
    Float_t         t1_event_index;
    Float_t         t1_jet_index;
    Float_t         t1_jets_e;
    Float_t         t1_jets_px;
    Float_t         t1_jets_py;
    Float_t         t1_jets_pz;
    Float_t         t1_jets_m;
    Float_t         t1_jets_theta;
    Float_t         t1_jets_phi;
    Float_t         t1_predicted[5];
    Float_t         t1_truths[5];
    
    // List of branches
    TBranch        *b_t1_event_index;   //!
    TBranch        *b_t1_jet_index;   //!
    TBranch        *b_t1_jets_e;   //!
    TBranch        *b_t1_jets_px;   //!
    TBranch        *b_t1_jets_py;   //!
    TBranch        *b_t1_jets_pz;   //!
    TBranch        *b_t1_jets_m;   //!
    TBranch        *b_t1_jets_theta;   //!
    TBranch        *b_t1_jets_phi;   //!
    TBranch        *b_t1_predicted;   //!
    TBranch        *b_t1_truths;   //!
    //!
    Float_t         t2_event_index;
    Float_t         t2_jet_index;
    Float_t         t2_jets_e;
    Float_t         t2_jets_px;
    Float_t         t2_jets_py;
    Float_t         t2_jets_pz;
    Float_t         t2_jets_m;
    Float_t         t2_jets_theta;
    Float_t         t2_jets_phi;
    Float_t         t2_predicted[5];
    Float_t         t2_truths[5];
    
    // List of branches
    TBranch        *b_t2_event_index;   //!
    TBranch        *b_t2_jet_index;   //!
    TBranch        *b_t2_jets_e;   //!
    TBranch        *b_t2_jets_px;   //!
    TBranch        *b_t2_jets_py;   //!
    TBranch        *b_t2_jets_pz;   //!
    TBranch        *b_t2_jets_m;   //!
    TBranch        *b_t2_jets_theta;   //!
    TBranch        *b_t2_jets_phi;   //!
    TBranch        *b_t2_predicted;   //!
    TBranch        *b_t2_truths;   //!

    
    
    tree1->SetBranchAddress("event_index", &t1_event_index, &b_t1_event_index);
    tree1->SetBranchAddress("jet_index", &t1_jet_index, &b_t1_jet_index);
    tree1->SetBranchAddress("jets_e", &t1_jets_e, &b_t1_jets_e);
    tree1->SetBranchAddress("jets_px", &t1_jets_px, &b_t1_jets_px);
    tree1->SetBranchAddress("jets_py", &t1_jets_py, &b_t1_jets_py);
    tree1->SetBranchAddress("jets_pz", &t1_jets_pz, &b_t1_jets_pz);
    tree1->SetBranchAddress("jets_m", &t1_jets_m, &b_t1_jets_m);
    tree1->SetBranchAddress("jets_theta", &t1_jets_theta, &b_t1_jets_theta);
    tree1->SetBranchAddress("jets_phi", &t1_jets_phi, &b_t1_jets_phi);
    tree1->SetBranchAddress("predicted", t1_predicted, &b_t1_predicted);
    tree1->SetBranchAddress("truths", t1_truths, &b_t1_truths);
    
    tree2->SetBranchAddress("event_index", &t2_event_index, &b_t2_event_index);
    tree2->SetBranchAddress("jet_index", &t2_jet_index, &b_t2_jet_index);
    tree2->SetBranchAddress("jets_e", &t2_jets_e, &b_t2_jets_e);
    tree2->SetBranchAddress("jets_px", &t2_jets_px, &b_t2_jets_px);
    tree2->SetBranchAddress("jets_py", &t2_jets_py, &b_t2_jets_py);
    tree2->SetBranchAddress("jets_pz", &t2_jets_pz, &b_t2_jets_pz);
    tree2->SetBranchAddress("jets_m", &t2_jets_m, &b_t2_jets_m);
    tree2->SetBranchAddress("jets_theta", &t2_jets_theta, &b_t2_jets_theta);
    tree2->SetBranchAddress("jets_phi", &t2_jets_phi, &b_t2_jets_phi);
    tree2->SetBranchAddress("predicted", t2_predicted, &b_t2_predicted);
    tree2->SetBranchAddress("truths", t2_truths, &b_t2_truths);
    
    
    
    tree1->Add(filename);
    tree2->Add(filename);
    //tree1->Print();
    
    
    TFile *hfile = hfile = TFile::Open("events_"+filename,"RECREATE");
    TTree *outtree = new TTree("event","event");

    outtree->Branch("event_index", &t1_event_index, "event_index/F");
    outtree->Branch("j1_jets_e", &t1_jets_e, "t1_jets_e/F");
    outtree->Branch("j1_jets_px", &t1_jets_px, "t1_jets_px/F");
    outtree->Branch("j1_jets_py", &t1_jets_py, "t1_jets_py/F");
    outtree->Branch("j1_jets_pz", &t1_jets_pz, "t1_jets_pz/F");
    outtree->Branch("j1_jets_m", &t1_jets_m, "t1_jets_m/F");
    outtree->Branch("j1_jets_theta", &t1_jets_theta, "t1_jets_theta/F");
    outtree->Branch("j1_jets_phi", &t1_jets_phi, "t1_jets_phi/F");
    outtree->Branch("j1_predicted", t1_predicted, "t1_predicted[5]/F");
    outtree->Branch("j1_truths", t1_truths, "t1_truths[5]/F");
    
    outtree->Branch("j2_jets_e", &t2_jets_e, "j2_jets_e/F");
    outtree->Branch("j2_jets_px", &t2_jets_px, "j2_jets_px/F");
    outtree->Branch("j2_jets_py", &t2_jets_py, "j2_jets_py/F");
    outtree->Branch("j2_jets_pz", &t2_jets_pz, "j2_jets_pz/F");
    outtree->Branch("j2_jets_m", &t2_jets_m, "j2_jets_m/F");
    outtree->Branch("j2_jets_theta", &t2_jets_theta, "j2_jets_theta/F");
    outtree->Branch("j2_jets_phi", &t2_jets_phi, "j2_jets_phi/F");
    outtree->Branch("j2_predicted", t2_predicted, "j2_predicted[5]/F");
    outtree->Branch("j2_truths", t2_truths, "j2_truths[5]/F");
    
 
    
    Long64_t nentries = tree1->GetEntries();

    Long64_t nbytes = 0, nb = 0;
    for (Long64_t jentry=0; jentry<nentries-1;jentry++) {
        tree1->GetEntry(jentry);
        tree2->GetEntry(jentry+1);
        if(t1_event_index == t2_event_index)
            cout << t1_event_index << "/" << jentry << endl;
            outtree->Fill();
    }
    outtree->Write();
    outtree->Print();
    hfile->Close();
}
void make_event_tree(void){
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_0.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_1.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_10.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_11.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_12.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_13.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_14.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_15.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_16.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_17.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_18.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_19.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_2.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_20.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_21.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_22.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_23.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_24.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_25.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_26.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_27.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_28.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_29.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_3.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_30.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_31.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_32.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_33.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_34.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_35.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_36.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_37.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_38.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_39.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_4.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_40.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_41.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_42.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_43.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_44.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_45.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_46.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_47.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_48.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_49.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_5.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_50.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_51.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_52.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_53.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_54.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_55.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_56.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_57.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_58.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_59.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_6.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_60.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_61.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_62.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_63.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_64.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_65.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_66.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_67.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_68.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_69.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_7.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_70.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_71.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_72.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_73.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_74.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_75.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_76.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_77.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_78.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_79.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_8.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_80.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_81.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_82.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_83.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_84.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_85.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_86.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_87.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_88.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_89.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_9.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_90.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_91.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_92.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_93.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_94.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_95.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_96.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_97.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_98.root");
do_stuff("raw_predictions_p8_ee_Zbb_ecm91_99.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_0.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_1.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_10.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_11.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_12.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_13.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_14.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_15.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_16.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_17.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_18.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_19.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_2.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_20.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_21.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_22.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_23.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_24.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_25.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_26.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_27.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_28.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_29.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_3.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_30.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_31.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_32.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_33.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_34.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_35.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_36.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_37.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_38.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_39.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_4.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_40.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_41.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_42.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_43.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_44.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_45.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_46.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_47.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_48.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_49.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_5.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_50.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_51.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_52.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_53.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_54.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_55.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_56.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_57.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_58.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_59.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_6.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_60.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_61.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_62.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_63.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_64.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_65.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_66.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_67.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_68.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_69.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_7.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_70.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_71.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_72.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_73.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_74.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_75.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_76.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_77.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_78.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_79.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_8.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_80.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_81.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_82.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_83.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_84.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_85.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_86.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_87.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_88.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_89.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_9.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_90.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_91.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_92.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_93.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_94.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_95.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_96.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_97.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_98.root");
do_stuff("raw_predictions_p8_ee_Zcc_ecm91_99.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_0.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_1.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_10.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_100.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_101.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_102.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_103.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_104.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_105.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_106.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_107.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_108.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_109.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_11.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_110.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_111.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_112.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_113.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_114.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_115.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_116.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_117.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_118.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_119.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_12.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_120.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_121.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_122.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_123.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_124.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_125.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_126.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_127.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_128.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_129.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_13.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_130.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_131.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_132.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_133.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_134.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_135.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_136.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_137.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_138.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_139.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_14.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_140.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_141.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_142.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_143.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_144.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_145.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_146.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_147.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_148.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_149.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_15.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_150.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_151.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_152.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_153.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_154.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_155.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_156.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_157.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_158.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_159.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_16.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_160.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_161.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_162.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_163.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_164.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_165.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_166.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_167.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_168.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_169.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_17.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_170.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_171.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_172.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_173.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_174.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_175.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_176.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_177.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_178.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_179.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_18.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_180.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_181.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_182.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_183.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_184.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_185.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_186.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_187.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_188.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_189.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_19.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_190.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_191.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_192.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_193.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_194.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_195.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_196.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_197.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_198.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_199.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_2.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_20.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_200.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_201.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_202.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_203.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_204.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_205.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_206.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_207.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_208.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_209.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_21.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_210.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_211.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_212.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_213.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_214.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_215.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_216.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_217.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_218.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_219.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_22.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_220.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_221.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_222.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_223.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_224.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_225.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_226.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_227.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_228.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_229.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_23.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_230.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_231.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_232.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_233.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_234.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_235.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_236.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_237.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_238.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_239.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_24.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_240.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_241.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_242.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_243.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_244.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_245.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_246.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_247.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_248.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_249.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_25.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_250.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_251.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_252.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_253.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_254.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_255.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_256.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_257.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_258.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_259.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_26.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_260.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_261.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_262.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_263.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_264.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_265.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_266.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_267.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_268.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_269.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_27.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_270.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_271.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_272.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_273.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_274.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_275.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_276.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_277.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_278.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_279.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_28.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_280.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_281.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_282.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_283.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_284.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_285.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_286.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_287.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_288.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_289.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_29.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_290.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_291.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_292.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_293.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_294.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_295.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_296.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_297.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_298.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_299.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_3.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_30.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_31.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_32.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_33.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_34.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_35.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_36.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_37.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_38.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_39.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_4.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_40.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_41.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_42.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_43.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_44.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_45.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_46.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_47.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_48.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_49.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_5.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_50.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_51.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_52.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_53.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_54.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_55.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_56.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_57.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_58.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_59.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_6.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_60.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_61.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_62.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_63.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_64.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_65.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_66.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_67.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_68.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_69.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_7.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_70.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_71.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_72.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_73.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_74.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_75.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_76.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_77.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_78.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_79.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_8.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_80.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_81.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_82.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_83.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_84.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_85.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_86.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_87.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_88.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_89.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_9.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_90.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_91.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_92.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_93.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_94.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_95.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_96.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_97.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_98.root");
do_stuff("raw_predictions_p8_ee_Zuds_ecm91_99.root");

}

